### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by HanJiexi** [owncloud/notes-iOS-App#29]
I just downloaded the app and it crashes immediately when opening it. Same with CloudNews. I am running the latest version of iOS on an iPad 3.

**Comment by phedlund** [comment]
Very odd. Please try deleting the app, rebooting the iPad, and then reinstall.

**Comment by HanJiexi** [comment]
Deleting the apps, rebooting iPad, and reinstalling has indeed resulted in the apps functioning correctly.

I wish the iPad would have allowed me to give you some kind of debugging info for when the problem first occurred... oh well.

**Comment by phedlund** [comment]
Good. If you sync your device with iTunes any crash logs will be available on your computer. You can search the web for information on where they will be located on your computer depending on operating system.

**Comment by HanJiexi** [comment]
Unfortunately iTunes doesn't support Ubuntu. But after searching I found that crash logs can be found in Settings > Privacy > Diagnostics & Usage on the iPad itself. Oddly, I can't find any logfile with a name like "CloudNews" or "CloudNotes". I also don't see anything like that in LatestCrash.ips or LatestCrash.plist. Either the crashes didn't generate a logfile or the logfile is under a name that I'm not recognizing.

**Comment by phedlund** [comment]
The names of the binaries are actually iOCNews and iOCNotes. Look for those among your logs.

**Comment by HanJiexi** [comment]
Strange — I can't find anything with those names anywhere... the only possibility is that the crash log would be buried somewhere inside one of the files with a name I'm not expecting. I tried looking in the LatestCrash log but didn't see it.
