### ISSUE TITLE
First line is halfly covered by header in edit mode

### ISSUE THREAD

**Issue by rakekniven** [owncloud/notes-iOS-App#30]
Running latest app version on iOS 9.

After selecting note to edit it my screen looks like

![img_4479-001](https://cloud.githubusercontent.com/assets/2069590/9992633/9a953378-6073-11e5-8a66-dc42d19df4d9.jpg)

Device iPhone 5s

**Comment by phedlund** [comment]
I am aware of this and I am working on a fix.
