### ISSUE TITLE
iOS7 support

### ISSUE THREAD

**Issue by rainforest1155** [owncloud/notes-iOS-App#39]
I was still using OwnCloud7 and thus had been stuck with an older OC Notes app. That's why I also didn't update the app on my iPhone4 in a long time. Now I finally upgraded my OwnCloud and when trying to update the app on my iPhone4, I noticed that the app is now requiring iOS8. 

My iPhone4 still works fine for me and I don't have any plans of updating it yet. Since it can't be updated past iOS7, would it be possible for you to add back support for it? Pretty please? 
Thank you very much!

**Comment by phedlund** [comment]
Sorry, but this is not going to happen.
