### ISSUE TITLE
setting up user on Iphone 6 - "error" notes not enabled for this user...."

### ISSUE THREAD

**Issue by wgregori** [owncloud/notes-iOS-App#40]
I'm running Owncloud 9.0.1.  When I try to setup a user on Own notes on iOS (iphone 6) I get the message that "notes is not enabled"... however, I can access notes via the web interface for this user.

**Comment by phedlund** [comment]
Make sure you have the latest version of Notes installed and enabled on your server. Download it from https://github.com/owncloud/notes/releases.

**Comment by wgregori** [comment]
more investigation has found that - the owncloud notes installation is working fine.  I'm able to set-up any owncloud user with the Android notes app.  Setup fails with all users on the iOS notes app.  The response is that "unable to find Notes application"..

**Comment by wgregori** [comment]
problem perhaps - the application is located in www/owncloud/apps/ownnote rather than www/owncloud/apps/note as is stated in the github distribution.

**Comment by wgregori** [comment]
I removed .../apps/ownnote and reinstalled Note - this resolved my inability to login - new problem though: all my notes disappeared and I'm unable to create a new note... looks like mysql is looking for the old directory perhaps...
