### ISSUE TITLE
Add i18n support to app

### ISSUE THREAD

**Issue by rakekniven** [owncloud/notes-iOS-App#42]
Add the moment english is the only localization language.
Please add i18n support and I will happily provide german translation.

**Comment by phedlund** [comment]
Already available. The files that need translations for German are in https://github.com/owncloud/notes-iOS-App/tree/master/iOCNotes/de.lproj.

**Comment by rakekniven** [comment]
Hello Peter,
just checked german files and they do not contain any translation.
My app shows some german words. See top area of attached screenshot.
Are they from iOS system?

General question about translation to german. Should I translate files and provide PR or is translation managed via transifex ( cannot check > not a member of owncloud project anymore)?

![2017-01-07 17-23-25 6005](https://cloud.githubusercontent.com/assets/2069590/21743247/84fda436-d4fe-11e6-9ad8-725f2bc82f22.png)

**Comment by phedlund** [comment]
Correct, they do not contain any translations, but they are available for anyone who wants to take on the task. The files are basically a list of key-value pairs where the values should be replaced by the localized string. 

A PR would be fine. There is currently no Transifex integration for this repository.

The German words you see are directly from iOS.

**Comment by rakekniven** [comment]
See #43

**Comment by phedlund** [comment]
I forgot about a few strings in https://github.com/owncloud/notes-iOS-App/blob/master/iOCNotes/Settings.bundle/de.lproj/Root.strings. Will you be able to translate those also?

**Comment by rakekniven** [comment]
Yes, I can do. Do I have to create another Branch/PR?

**Comment by phedlund** [comment]
Thanks. You can probably use the same branch. I don't know if you need to recreate the PR or if it is automatically reopened.

**Comment by rakekniven** [comment]
See #44

**Comment by phedlund** [comment]
German is fully supported. Other languages can be requested.
