### ISSUE TITLE
Size limit?

### ISSUE THREAD

**Issue by nanaya** [owncloud/notes-iOS-App#45]
I wonder if there's some kind of size limit. I have one not-so-large file which crashes when opened through the app. Unfortunately I can't share the file because it contains private data.

I don't know what causes it but I made two files which also crashes the app (on iphone se, 10.3). Server is running nextcloud 11.0.2.

https://s.myconan.net/2017-03/New%20note%20%282%29.txt
https://s.myconan.net/2017-03/New%20note.txt

**Comment by phedlund** [comment]
It appears those files make the app crash due to device memory issues. I'll look into what can be done to handle that more gracefully.

**Comment by phedlund** [comment]
Large files no longer cause any issues.
