### ISSUE TITLE
Notes could not be found on your server error

### ISSUE THREAD

**Issue by farynam** [owncloud/notes-iOS-App#46]
When I try to connect to Owncloud server in my local network I receive following message: "Notes could not be found on your server. Make sure it is installed and enabled". 
Owncloud server which I use: 10.0.7.2
QOwnNotesAPI:  17.7.0
IOS CloudNotes: 2.1.1 (13 Nov 2017)

my connection configuraion:
Server: https://192.168.0.32/index.php
Allow Untrusted SSL Certificate: checked

However my local installation works great with osx installation of:
QOwnNotes - version 18.03.6 - Travis CI - build 3515

**Comment by phedlund** [comment]
What makes you think the app should work with QOwnNotes? It's designed for ownCloud/NextCloud Notes. You need to install the latest version of Notes (https://github.com/nextcloud/notes/releases) on your server.

**Comment by phedlund** [comment]
I see. That's a very misleading statement. I would file a bug report with them to revise the text.
