### ISSUE TITLE
subdirectories as categories

### ISSUE THREAD

**Issue by bjo81** [owncloud/notes-iOS-App#49]
Other Notes-apps (e.g. Nextcloud Notes App for Android, QOwnNotes) have the ability to create subdirectories, the Android app show them as categories. CloudNotes show only the Notes, without any possibility of choosing a subdirectory or category.

**Comment by GeorgFoc** [comment]
Yes it would be great to have the Ability to use Directories. I manage many Notebooks with QOwnnotes and when i create a new note in the app, it always goes to the Notes/ Directory without the option to create it in a subdirectory.

**Comment by phedlund** [comment]
Category support was added in version 3.0.0.
