### ISSUE TITLE
Checking out project issues

### ISSUE THREAD

**Issue by muzzah** [owncloud/notes-iOS-App#50]
Hey

Ive been trying to get the project building from checkout after doing a recursive checkout but having some issues. Would be great if you guide me in the right direction. I can then submit a PR to fix the issues.

Im initially getting a problem with the Marklight git submodule. Seems as though maybe some of the references have changed and it cannot find the specific commit.

```
....
Submodule path 'KVNProgress': checked out 'afc2bf451c0f1e4af52068ad497c0d7414009738'
Submodule path 'Markingbird': checked out '42997bc726f9fdf2fd9a4bcca9e9112ceb36482f'
error: Server does not allow request for unadvertised object 679f4bdd02ebd3065d640574c56ce4eb9606c33e
Fetched in submodule path 'Marklight', but it did not contain 679f4bdd02ebd3065d640574c56ce4eb9606c33e. Direct fetching of that commit failed.
``` 

Having a look at the project on github, it seems the commit is there (on the development branch and not master) but git cannot update the submodule correctly. Im wondering if the maintainer is not seeing this issue because of the historical references that might be on his computer and he has not updated the submodule in a while?

If I go into the project and do `git reset --hard` then I am bascially at head but then get a compilation issues with a file named 'PureLayout.h' not being found on an line importing it in a bridging header. Could you advise as where this should file be? Is it meant to be in the project or in one of the submodules?

```
/Users/..../Workspace/notes-iOS-App/iOCNotes/BridgingHeader.h:12:9: error: 'PureLayout.h' file not found
#import "PureLayout.h"
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/.../Library/Developer/Xcode/DerivedData/iOCNotes-gjrbxvuoigknwfadakskuftsyold/Build/Intermediates.noindex/PrecompiledHeaders/BridgingHeader-swift_2HLW8TVWCQQJA-clang_BHR5KUNTH5NO.pch' for bridging header '/Users/.../Workspace/notes-iOS-App/iOCNotes/BridgingHeader.h'
````

**Comment by muzzah** [comment]
So upon further investigation there are a number of submodules that do not contain any files after doing `git submodule update`. Not sure why this is happening but once again doing a `git reset --hard` in each of those directories then populates them but i suspect that they are not the correct commit and I end up having a lot of compilation problems.

**Comment by phedlund** [comment]
The offending commit can be found here: https://github.com/phedlund/Marklight/commit/679f4bdd02ebd3065d640574c56ce4eb9606c33e

I apologize for the mix up.

**Comment by phedlund** [comment]
To build the project you also need a binary of https://github.com/kstenerud/KSCrash.

Or comment out the crash reporting stuff.

**Comment by muzzah** [comment]
> The offending commit can be found here: [phedlund/Marklight@679f4bd](https://github.com/phedlund/Marklight/commit/679f4bdd02ebd3065d640574c56ce4eb9606c33e)
> 
> I apologize for the mix up.

Sorry slightly confused. I see you reference a commit on your forked version of Marklight, but notes ios app repo references the original Marklight repo. So I am assuing the submodule just needs to be updated to point to your fork? 

Have you thought about how you want to handle the KSCrash dependency? I noticed that you dont have any kind of dependency manager setup within the project. Im not a huge fan of submodules and for a project like this, Cocoapods or something similar could work. Thoughts?

**Comment by phedlund** [comment]
OK, thanks. The next version will use Carthage. Cocoapods is a huge pain in my opinion.

**Comment by phedlund** [comment]
The project now uses Carthage. Most third-party libraries have been changed to ones written in Swift.
