### ISSUE TITLE
New notes do not appear within the Notes app

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/notes-iOS-App#54]
In the iOS notes app I created new notes but they do not appear within the Notes app of my Nextcloud server instance.

Using the latest version of your iOS app and notes server app both. And Nextcloud v15.

Also strangely, the notes I have on the server do not appear on your iOS app.

Not sure if it's a bug or a wrong setting? I've used the URL pointing to the index.php of the Nextcloud server. Or is that wrong?

**Comment by phedlund** [comment]
Normally you would use `https://myserver.com/nextcloud` when logging in from CloudNotes. If pretty URLs are not properly configured on the server, the app will attempt to work around that by adding `/index.php`. You should not have to do that.

When you tap Connect from the login screen, do you get any error message? If the login is successful you should be offered to sync your notes.

**Comment by binarykitchen** [comment]
Yup, already done all that. Still no luck. And no error message comes at all.

It worked fine in an older version! Then one of your newer versions broke it totally.

As a programmer myself I'm pretty sure there is a weird bug somewhere ...

**Comment by phedlund** [comment]
Can you contact me directly at support@pbh.dev?

**Comment by phedlund** [comment]
Uninstalling and reinstalling the app resolved the syncing problem.
