### ISSUE TITLE
Support Two-Factor TOTP Provider

### ISSUE THREAD

**Issue by mucke5** [owncloud/notes-iOS-App#55]
Hello. I bought your app and I can't log in to my account. Can you please support 2fa? Thanks for your answer.
---
https://apps.nextcloud.com/apps/twofactor_totp

**Comment by phedlund** [comment]
It works fine for me. Did you generate an app password for CloudNotes in your user's security settings?

**Comment by mucke5** [comment]
Thanks. That worked ;)
