### ISSUE TITLE
Read mode icon does not match other icons

### ISSUE THREAD

**Issue by hellojaccc** [owncloud/notes-iOS-App#74]
![image](https://user-images.githubusercontent.com/71537512/138982868-d78ec92b-bd6e-40ff-b5a7-c580761979a4.jpeg)

![image](https://developer.apple.com/design/human-interface-guidelines/glyphs/images/abstract-text-in-glyph_2x.png)

Can it use this icon?

**Comment by phedlund** [comment]
I will use 
<img width="127" alt="Screen Shot 2021-11-14 at 6 40 53 PM" src="https://user-images.githubusercontent.com/884639/141713826-208bc6cb-0dff-4a15-b7d9-879faf7b7f31.png">
