### ISSUE TITLE
Can't share notes from 'Notes' view

### ISSUE THREAD

**Issue by hellojaccc** [owncloud/notes-iOS-App#78]
https://user-images.githubusercontent.com/71537512/141305291-e852a143-50ff-4154-ba31-089ff5fb6279.MOV

Please check the attachment.

**Comment by phedlund** [comment]
I can share to the Files app just fine. What specifically are you trying to do?

**Comment by hellojaccc** [comment]
It works : share button from specific note
It doesn't work : share button when long pressed a note in main screen
